apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-ui.fullname" . }}
  labels:
    {{- include "external-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "external-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "external-ui.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
